/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    // プレイヤーの生成(朝野)
    Player player = new Player("OIT");

    player.showDeck();


    //バトル処理(佐藤)
  }

}
