/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {

    // デバッグ用
    SeMonsterGame game = new SeMonsterGame();
    // Monster monster;
    // Scanner scan = new Scanner(System.in);
    String name = "test";
    game.addPlayer(name);
    game.battle(new Monster(), 0);
    // scan.close();
  }

}
